#spring.application.name=jobporal
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_portal
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #    thay vi viet cac cau lenh vi du select * from name_table thi ta se thao tac voi cac doi tuong duoc
    #    anh xa tu csdl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #cac cau lenh thay doi cau truc(tao bang, them cot) database se khong duoc dung
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8088


